name: chemspinx
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - rdkit
  - pip:
    - sphinx
    - ipykernel
    - ipywidgets
    - pubchempy
    - py3dmol
    - nbsphinx
    - ghp-import
    - jupytext
    - Pygments
    - sphinxcontrib-bibtex
    - sphinxcontrib-svg2pdfconverter

