 #Python CircleCI 2.0 configuration file
#
# Inspired by: https://github.com/spatialaudio/nbsphinx/blob/master/.circleci/config.yml
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build_docs:
    docker:
      # https://github.com/dante-ev/docker-texlive
      - image: danteev/texlive

    working_directory: ~/checkout

    environment:
      MINICONDA: $HOME/miniconda

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "environment.yml" }}
            # fallbacks
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: Installing apt Packages
          command: |
            echo "export PATH=$MINICONDA/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -b -p $MINICONDA
            conda env create -n sphinxenv -f environment.yml
            source activate sphinxenv
            apt-get update && apt-get install -y librsvg2-bin pandoc #python-rdkit librdkit1 rdkit-data
            rm ~/miniconda.sh
      - save_cache:
          paths:
            - $MINICONDA/
          key: v1-deps-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          name: Building HTML - there is no cache atm?
          command: |
            source activate sphinxenv
            python3 -m sphinx . build
            #Hacky way of giving the gh-pages branch a possibly README
            # and masking any HTML rendered README...
            cp README.md build/ 2>/dev/null
            rm -f build/README.html
      - run:
          name: Pushing to gh-pages
          command: |
            # CircleCI ignore gh-pages https://discuss.circleci.com/t/cant-ignore-the-gh-pages-branch/2002
            source activate sphinxenv
            ghp-import -p -n -f -m 'auto commit gh-pages [ci skip]' -r https://${GITHUB_PERSONAL_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git build
workflows:
  version: 2
  build:
    jobs:
      - build_docs:
          filters:
            branches:
              only:
                - master
              ignore:
                - gh-pages
