 #Python CircleCI 2.0 configuration file
#
# Inspired by: https://github.com/spatialaudio/nbsphinx/blob/master/.circleci/config.yml
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build_docs:
    docker:
      # https://github.com/dante-ev/docker-texlive
      - image: danteev/texlive

    working_directory: ~/checkout

    environment:
      PIP_INSTALL: pip install --progress-bar off --upgrade

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
            # fallbacks
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: Installing apt Packages
          command: |
            apt-get update
            apt-get install -y librsvg2-bin #python-rdkit librdkit1 rdkit-data
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -b -p ~/miniconda
            rm ~/miniconda.sh
      - run:
          name: Installing py and conda dependencies
          command: |
            export PATH=~/miniconda/bin/:$PATH
            conda env create -f environment.yml
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Building HTML - there is no cache atm?
          command: |
            #this needs to be the conda python FFS
            export PATH=~/miniconda/bin/:$PATH
            conda activate sphinxenv
            python3 -m sphinx . build
            #Hacky way of giving the gh-pages branch a possibly README
            # and masking any HTML rendered README...
            cp README.md build/ 2>/dev/null
            rm -f build/README.html
      - run:
          name: Pushing to gh-pages
          command: |
            # CircleCI ignore gh-pages https://discuss.circleci.com/t/cant-ignore-the-gh-pages-branch/2002
            export PATH=~/miniconda/bin/:$PATH
            conda activate sphinxenv
            ghp-import -p -n -f -m 'auto commit gh-pages [ci skip]' -r https://${GITHUB_PERSONAL_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git build
workflows:
  version: 2
  build:
    jobs:
      - build_docs:
          filters:
            branches:
              only:
                - master
              ignore:
                - gh-pages
